### ISSUE TITLE
grunt serve dies with port 9000 already in use

### ISSUE THREAD

**Issue by spacemonkey** [vesparny/angular-kickstart#2]
Ciao Alessandro! A clean install results in grunt serve failing with port 9000 already in use, and I'm assuming test or some such is hogging that port when the server tries to fire up.

Might have something to do with angular-generator? See https://github.com/yeoman/yeoman/issues/1118

``` bash
ng-kickstart mpirtle$ grunt serve
Running "clean:dist" (clean) task

Running "clean:tmp" (clean) task
Cleaning build/tmp/assets...OK
Cleaning build/tmp/index.html...OK
Cleaning build/tmp/templates-app.js...OK
Cleaning build/tmp/templates-common.js...OK
Cleaning build/tmp/webapp...OK

Running "html2js:app" (html2js) task
Successfully converted 3 html templates to js.

Running "html2js:common" (html2js) task
Successfully converted 0 html templates to js.

Running "concurrent:build" (concurrent) task

    Running "copy:webappJs" (copy) task
    Copied 8 files

    Done, without errors.

    Running "copy:vendorJs" (copy) task
    Copied 7 files

    Done, without errors.

    Running "copy:vendorCss" (copy) task
    Copied 4 files

    Done, without errors.

    Running "sass:dev" (sass) task
    File "build/tmp/assets/css/0.0.1.style.css" created.

    Done, without errors.

Running "copy:webappAssets" (copy) task
Created 3 directories, copied 9 files

Running "tpl:build" (tpl) task

Running "configureProxies" task
Proxy created for: /api to localhost:9001

Running "connect:livereload" (connect) task
Fatal error: Port 9000 is already in use by another process.
```

**Comment by nathiyakumar** [comment]
Running "injector:dev" (injector) task
Missing option `template`, using `dest` as template instead
Injecting css files (2 files)
>> Nothing changed

Running "concurrent:tasks" (concurrent) task
    Running "connect:server" (connect) task
    Waiting forever...
    Fatal error: Port 4000 is already in use by another process.
    
    
    Execution Time (2017-05-25 17:47:46 UTC+5:30)
    loading tasks   587ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 96%
    connect:server   24ms  ▇▇ 4%
    Total 612ms
    
    Running "watch" task
    Waiting...
Warning:  Used --force, continuing.

Done, but with warnings.


Execution Time (2017-05-25 17:47:45 UTC+5:30)
loading tasks     532ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 27%
injector:dev      393ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 20%
concurrent:tasks     1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 53%
Total 2s

**Comment by nathiyakumar** [comment]
how to  solve this error in linux?
