### ISSUE TITLE
Dev dependencies are out of date

### ISSUE THREAD

**Issue by lowe0292** [vesparny/angular-kickstart#22]
I'm about to start a new angular project, and this is my frontrunner as far as kickstarters/generators go, but the [out of date dependencies](https://david-dm.org/vesparny/angular-kickstart#info=devDependencies) are a small cause for concern.

Any plans to update them?

**Comment by vesparny** [comment]
hey yes I know,
don't have so much free time in this moment.
Would you like to try to update deps an see if everything i working as expected?

**Comment by lowe0292** [comment]
I bumped everything to the latest on the off chance it would work, but unfortunately it did not. :[

`gulp serve` threw an error due to some syntax changes in [gulp-ruby-sass](http://stackoverflow.com/questions/28140012/gulp-typeerror-arguments-to-path-join-must-be-strings)

**Comment by vesparny** [comment]
ok, can you paste here your package.json?

--
Alessandro Arnodo


On Wed, Mar 25, 2015, at 09:34 PM, Scott Lowe wrote:
> I bumped everything to the latest on the off chance it would work, but
> unfortunately it did not. :[


> gulp serve threw an error due to some syntax changes in
> gulp-ruby-sass[1]


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. http://stackoverflow.com/questions/28140012/gulp-typeerror-arguments-to-path-join-must-be-strings
  2. https://github.com/vesparny/angular-kickstart/issues/22#issuecomment-86204696

**Comment by lowe0292** [comment]
[Sure thing](https://gist.github.com/lowe0292/61cda721eb22220c7cb4)!

**Comment by vesparny** [comment]
ok.
I think it's just a matter of updating libraries and use new apis, it won't be so complicated

**Comment by lowe0292** [comment]
Cool!

For clarity, are you working on it or should I? Don't want to duplicate or efforts. :]

**Comment by vesparny** [comment]
I think I wouldn't have time until the next weekend.
anyways...PR are always welcome :)
