### ISSUE TITLE
Serve different port?

### ISSUE THREAD

**Issue by gpinkham** [vesparny/angular-kickstart#27]
I changed the build config's port reference to 8000 but gulp sill serves up on port 3000 (or 3001 if it's in use)..    I'm doing an OAuth callback so for dev I need this port locked to 8000. . Any clue how to change it?    Big Thanks for this project..  helped "kickstart" my angular learning..

**Comment by gpinkham** [comment]
found it..   realized it was browser-sync not gulp I needed to tell about it..   for future reference I used: 
`````
gulp.task('serve', ['build'], function() {
  browserSync({
    port: config.port,
    ui: {
      port: config.uiPort
    },
    notify: false,
    logPrefix: pkg.name,
    server: ['build', 'client']
  });
...
`````
and put a setting in the build/build.config.js file

**Comment by vesparny** [comment]
Actually you raised a good point.
Do you mind a PR?
